### PR TITLE
Kubernetes integration

### PR DESCRIPTION
**Pull request by pboothe**
Use k8s and not the operator repo.  Also, perform all local testing in containers.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/24)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[sync.py, line 389 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/24#-KnZyDXsMl5kGJzK0au_:-KnZyDXsMl5kGJzK0aua:bco4ggl) ([raw file](https://github.com/m-lab/scraper-sync/blob/473d098675f33cc21b7a3acf5de8deb05cc72a0a/sync.py#L389)):*
> ```Python
>     conn = httplib.HTTPSConnection('kubernetes.default.svc', context=context)
>     conn.request('GET',
>                  'https://kubernetes/apis/extensions/v1beta1/deployments',
> ```

Is it intended to use a different hostname here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/24#-:-KnZz4q4Pk_CbYNePfhx:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pre-commit.sh, line 11 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/24#-KnZzRBDuBRCymXE8dv9:-KnZzRBEao1ldTb5vIiA:b-xwgavr) ([raw file](https://github.com/m-lab/scraper-sync/blob/473d098675f33cc21b7a3acf5de8deb05cc72a0a/pre-commit.sh#L11)):*
> ```Shell
> 
> docker build . -f Dockerfile -t sync
> docker build . -f TestDockerfile -t synctest
> ```

fyi, my questions earlier about git ls-files vs find was due to expecting the docker command here to use a `-v` mount point and using the existing test scripts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/24)*

**Review by stephen-soltesz — APPROVED** [review]

**Comment by pboothe** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[sync.py, line 389 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/24#-KnZyDXsMl5kGJzK0au_:-Kn_5LWCumz5vnD-1AV8:b-gjzhto) ([raw file](https://github.com/m-lab/scraper-sync/blob/473d098675f33cc21b7a3acf5de8deb05cc72a0a/sync.py#L389)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it intended to use a different hostname here?
</blockquote></details>

No! Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/24)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/24#-:-Kn_JeDn-YeE1HeDAFuW:bnfp4nl)*

**Pull request merged**
