### PR TITLE
Staging autodeploy for scraper sync

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/10)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklGWTA5eEW6zQnbg6m:-KklGWTBOHJWgQmnNlYJ:bmcp0kh) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/.travis.yml#L16)):*
> yes | ${HOME}/google-cloud-sdk/bin/gcloud components install kubectl

Please:

 * install kubectl from `install_gcloud.sh`, maybe optionally.
 * set `gcloud config set core/disable_prompts true` so the `yes |` is unnecessary.

---

*[deploy.sh, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklHDuQ32U-NqBcBCtS:-KklHDuQ32U-NqBcBCtT:beh2mu5) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Please add a one sentence docstring for the prupose of this script.

---

*[deploy.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklHvlHhdV7GtYCYWOK:-KklHvlHhdV7GtYCYWOL:bp08gaa) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L12)):*
> ```Shell
> mkdir deployment
> cp deploy.yml deployment
> if [[ "$1" = staging ]]
> ```

Since this is bash, I suggest using the `==` form for clarity.

---

*[deploy.sh, line 14 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklIjsJ_qHVwDtMatvY:-KklIjsJ_qHVwDtMatvZ:bw7j0lo) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L14)):*
> ```Shell
> if [[ "$1" = staging ]]
> then
>   gcloud auth activate-service-account --key-file /tmp/staging-secret-key.json
> ```

Naming the keys after the GCP project makes it simpler to derive many parameters from just the project id.

---

*[deploy.sh, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklIHEiQ9kGjP5Rk8MA:-KklIHEiQ9kGjP5Rk8MB:bvp70wf) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L16)):*
> ```Shell
>   gcloud auth activate-service-account --key-file /tmp/staging-secret-key.json
>   ./travis/build_and_deploy_container.sh ${TRAVIS_COMMIT} \
>     gcr.io/mlab-staging/github-m-lab-scraper mlab-staging scraper-cluster us-central1-a \
> ```

There are a number of constants here. What is the plan for making this operate on mlab-oti project as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10)*

**Comment by pboothe** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklGWTA5eEW6zQnbg6m:-Kkqbvr63LCZMUfwmTRc:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/.travis.yml#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> yes | ${HOME}/google-cloud-sdk/bin/gcloud components install kubectl

Please:

 * install kubectl from `install_gcloud.sh`, maybe optionally.
 * set `gcloud config set core/disable_prompts true` so the `yes |` is unnecessary.

</blockquote></details>

Done.

---

*[deploy.sh, line 1 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklHDuQ32U-NqBcBCtS:-KkqbwgmQpuxtngbArbA:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a one sentence docstring for the prupose of this script.
</blockquote></details>

Done.

---

*[deploy.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklHvlHhdV7GtYCYWOK:-KkqbxM4N_XphfbQGsUF:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this is bash, I suggest using the `==` form for clarity.
</blockquote></details>

Done.

---

*[deploy.sh, line 14 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklIjsJ_qHVwDtMatvY:-Kkqbywa4vHPsK-IugiH:bhcqilp) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Naming the keys after the GCP project makes it simpler to derive many parameters from just the project id.
</blockquote></details>

This and the next comment were addressed in a possibly-unexpected way.

---

*[deploy.sh, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklIHEiQ9kGjP5Rk8MA:-Kkqc2tmvms6fmdWQClA:b-q64pkt) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/deploy.sh#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There are a number of constants here. What is the plan for making this operate on mlab-oti project as well?
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 16 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KklGWTA5eEW6zQnbg6m:-KkrCYEJ15XNaRAYwGhP:b-9755fn) ([raw file](https://github.com/m-lab/scraper-sync/blob/8728bb3ac6d17ef91671852838e0e872a305a1db/.travis.yml#L16)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!

---

*[deploy.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkrD5xhrxziqi9cWNjz:-KkrD5xhrxziqi9cWNk-:b-bm856e) ([raw file](https://github.com/m-lab/scraper-sync/blob/d120065eb1a76a64482a628f728816a6cc34a25c/deploy.sh#L11)):*
> ```Shell
> source "${HOME}/google-cloud-sdk/path.bash.inc"
> 
> ssh-keygen -f ~/.ssh/google_compute_engine -N ""
> ```

I suspect this is not necessary. Please remove, unless it's needed. If it's needed, please add a comment explaining why.

---

*[deploy.sh, line 31 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkrEKxvABBVowuOem87:-KkrEKxvABBVowuOem88:b-rreftu) ([raw file](https://github.com/m-lab/scraper-sync/blob/d120065eb1a76a64482a628f728816a6cc34a25c/deploy.sh#L31)):*
> ```Shell
> elif [[ "$1" == sandbox-* ]]; then
>   SANDBOXSUFFIX=$(echo "$1" | sed -e 's/^sandbox-//')
>   [[ -n "${CLUSTERPREFIX}" ]] || exit 1
> ```

When is `CLUSTERPREFIX` set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-:-KkrH3S8fOBnz4aem-Xb:bnfp4nl)*

**Comment by pboothe** [comment]
PTAL, I think you will prefer this new way of doing things.

**Comment by stephen-soltesz** [comment]
Thanks, this is looking much better! A few more suggestions.

---

Reviewed 1 of 3 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 20 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvPuHwMH2Xno1Thfuz:-KkvPuHxR1v1oXIktNic:b-5mn1k4) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/.travis.yml#L20)):*
> ```YAML
> deploy:
> - provider: script
>   script: $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /tmp/sandbox-secret-key.json && cd $TRAVIS_BUILD_DIR && ./deploy.sh $TRAVIS_BRANCH
> ```

Please call these preconditions from within `deploy.sh`.

---

*[deploy.sh, line 35 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNMrrSwtC5HU-hKG9:-KkvNMrrSwtC5HU-hKGA:b-cbpq25) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L35)):*
> ```Shell
>   ./travis/substitute_values.sh deployment \
>     IMAGE_URL gcr.io/mlab-oti/github-m-lab-scraper-sync:${GIT_COMMIT} \
>     SPREADSHEET_ID 143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY \
> ```

Should the sheet IDs be the same for staging and production?

---

*[deploy.sh, line 39 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNEL4y2YvxXpK_xwX:-KkvNEL5vukQjUFr_fyn:b-61v83n) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L39)):*
> ```Shell
>     GITHUB_COMMIT http://github.com/m-lab/scraper-sync/tree/${GIT_COMMIT}
>   ./travis/build_and_push_container.sh \
>     gcr.io/mlab-oti/github-m-lab-scraper-sync:${GIT_COMMIT}  mlab-staging
> ```

typo? s/mlab-staging/mlab-oti/

---

*[deploy.sh, line 55 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvO5lUkzVh5661FeEg:-KkvO5lUkzVh5661FeEh:bsylfoe) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L55)):*
> ```Shell
>   SANDBOXSUFFIX=$(echo "$1" | sed -e 's/^sandbox-//')
>   [[ -n "${SANDBOXSUFFIX}" ]] || exit 1
>   ./travis/substitute_values.sh deployment \
> ```

There's significant overlap in each block above. Rather than calling each script, I suggest just setting the variables that the three primary commands require. Then there is a single place where these scripts actually run.

This also helps draw attention to the essential differences in each block, which should help spot typos in values that are out of place.

For example:
```
if [[ "$1" == production ]]; then
  PROJECT=mlab-oti
  SHEET_ID=143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY
  CLUSTER=scraper-cluster
  ZONE=us-central1-a
elif ...
  # etc..
fi

./travis/substitute_values.sh deployment \
    IMAGE_URL gcr.io/${PROJECT}/github-m-lab-scraper-sync:${GIT_COMMIT} \ 
    SPREADSHEET_ID ${SHEET_ID} \
    NAMESPACE scraper \
    GITHUB_COMMIT http://github.com/m-lab/scraper-sync/tree/${GIT_COMMIT}

  ./travis/build_and_push_container.sh \
    gcr.io/${PROJECT}/github-m-lab-scraper-sync:${GIT_COMMIT}  ${PROJECT}

  gcloud --project=${PROJECT} container clusters get-credentials ${CLUSTER} --zone=${ZONE}
  kubectl apply -f deployment/
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-:-KkvQD3qLl68zYMi8cAT:bnolhw)*

**Comment by pboothe** [comment]
Responded.

---

Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 20 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvPuHwMH2Xno1Thfuz:-KkvuM85-vh9vNzWkWW6:b-x5cudl) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/.travis.yml#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please call these preconditions from within `deploy.sh`.
</blockquote></details>

These preconditions are only required for travis and not for local deployment, so putting them here simplifies the deployment script. I have therefore complicated the script. If you prefer it, we can keep it.

---

*[deploy.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkrD5xhrxziqi9cWNjz:-KkvubD8iKwEL9Vo8ZZi:b73x84b) ([raw file](https://github.com/m-lab/scraper-sync/blob/d120065eb1a76a64482a628f728816a6cc34a25c/deploy.sh#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suspect this is not necessary. Please remove, unless it's needed. If it's needed, please add a comment explaining why.
</blockquote></details>

Changed how the args work to explicitly signal whether or not the deployment is occurring on travis.

---

*[deploy.sh, line 31 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkrEKxvABBVowuOem87:-KkvxdzuylPQvrYPIAUD:b-7ivu58) ([raw file](https://github.com/m-lab/scraper-sync/blob/d120065eb1a76a64482a628f728816a6cc34a25c/deploy.sh#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When is `CLUSTERPREFIX` set?
</blockquote></details>

Now correctly using SANDBOXSUFFIX

---

*[deploy.sh, line 35 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNMrrSwtC5HU-hKG9:-KkvxM3cKr5s1FaqjTRv:bc4genc) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should the sheet IDs be the same for staging and production?
</blockquote></details>

For now it doesn't hurt anything.

---

*[deploy.sh, line 39 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNEL4y2YvxXpK_xwX:-KkvxcAf4mW2K34jtldo:b-73m6vw) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

typo? s/mlab-staging/mlab-oti/
</blockquote></details>

Nice catch!

---

*[deploy.sh, line 55 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvO5lUkzVh5661FeEg:-Kkvzra86w4vI_RAOLld:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There's significant overlap in each block above. Rather than calling each script, I suggest just setting the variables that the three primary commands require. Then there is a single place where these scripts actually run.

This also helps draw attention to the essential differences in each block, which should help spot typos in values that are out of place.

For example:
```
if [[ "$1" == production ]]; then
  PROJECT=mlab-oti
  SHEET_ID=143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY
  CLUSTER=scraper-cluster
  ZONE=us-central1-a
elif ...
  # etc..
fi

./travis/substitute_values.sh deployment \
    IMAGE_URL gcr.io/${PROJECT}/github-m-lab-scraper-sync:${GIT_COMMIT} \ 
    SPREADSHEET_ID ${SHEET_ID} \
    NAMESPACE scraper \
    GITHUB_COMMIT http://github.com/m-lab/scraper-sync/tree/${GIT_COMMIT}

  ./travis/build_and_push_container.sh \
    gcr.io/${PROJECT}/github-m-lab-scraper-sync:${GIT_COMMIT}  ${PROJECT}

  gcloud --project=${PROJECT} container clusters get-credentials ${CLUSTER} --zone=${ZONE}
  kubectl apply -f deployment/
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-:-Kkvzt2oPABpG-TsV6Mb:b-123qe9)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
:lgtm: Thank you for the updates!

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.travis.yml, line 20 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvPuHwMH2Xno1Thfuz:-Kkw5FCr2ZIR5sVLr-4S:biah7kf) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/.travis.yml#L20)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

These preconditions are only required for travis and not for local deployment, so putting them here simplifies the deployment script. I have therefore complicated the script. If you prefer it, we can keep it.
</blockquote></details>

Keeping the complexity out of the travis config is preferable, since this file is not really a language. It's even more primitive than a bash script.

---

*[deploy.sh, line 35 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNMrrSwtC5HU-hKG9:-Kkw22kgp2amqjFkRFxe:b-r2qfo6) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L35)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

For now it doesn't hurt anything.
</blockquote></details>

When will it matter? Please add a TODO to separate them.

---

*[deploy.sh, line 53 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw3HcMF2NkfJaS_Dhg:-Kkw3HcMF2NkfJaS_Dhh:b-f2u6vi) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L53)):*
> ```Shell
>   SHEET_ID=143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY
>   NAMESPACE=scraper-${SANDBOXSUFFIX}
>   CLUSTER=${SANDBOXSUFFIX}-scraper-cluster
> ```

Why is `SANDBOXSUFFIX` used as a suffix and then prefix?

If everything is contained within a cluster, does the `NAMESPACE` need to have a suffix at all? Could that be constant across all clusters?

---

*[deploy.sh, line 72 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw4OiW9Xo_jZB-Q9HH:-Kkw4OiW9Xo_jZB-Q9HI:bm72pg3) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L72)):*
> ```Shell
> fi
> 
> ./travis/substitute_values.sh deployment \
> ```

Please add simple comments about the work this sequence is performing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-:-Kkw4ILL2EtQ2_3vkiHF:bjvl3sz)*

**Comment by pboothe** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[deploy.sh, line 35 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-KkvNMrrSwtC5HU-hKG9:-Kkw7ADqkB518z0ji00D:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/14f15398e493de454ff354cecab517c9cb38254e/deploy.sh#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When will it matter? Please add a TODO to separate them.
</blockquote></details>

Done.

---

*[deploy.sh, line 53 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw3HcMF2NkfJaS_Dhg:-Kkw7GCLoM014cDSYZht:b2z99f4) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why is `SANDBOXSUFFIX` used as a suffix and then prefix?

If everything is contained within a cluster, does the `NAMESPACE` need to have a suffix at all? Could that be constant across all clusters?
</blockquote></details>

Updated comments with an explanation.

---

*[deploy.sh, line 72 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw4OiW9Xo_jZB-Q9HH:-Kkw7AocZ9RTCbXpGlEk:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L72)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add simple comments about the work this sequence is performing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10)*

**Comment by stephen-soltesz** [comment]
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[deploy.sh, line 53 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw3HcMF2NkfJaS_Dhg:-KkwBXtpBqNqBb0B-K-G:bea9ta9) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L53)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Updated comments with an explanation.
</blockquote></details>

Oooh, I was thinking this is the namespace defined in `namespace.yml`.  This is the *datastore* namespace!!

Making this distinction clearer would be welcome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10)*

**Comment by pboothe** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[deploy.sh, line 53 at r4](https://reviewable.io:443/reviews/m-lab/scraper-sync/10#-Kkw3HcMF2NkfJaS_Dhg:-KkwN0-BAMAxVjSv_ZG3:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/db6ab6b16b6ad23505c525f50b202e87653531ab/deploy.sh#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oooh, I was thinking this is the namespace defined in `namespace.yml`.  This is the *datastore* namespace!!

Making this distinction clearer would be welcome.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/10)*

**Pull request merged**
