### PR TITLE
Deploy to prod on tag

### PR DESCRIPTION
**Pull request by pboothe**
Deploy to prod on TAG.
Deploy to staging on push to master.
Also updates the pre-commit unit tests to run in a docker container, so we won't have any surprises about whether the code works in the actual container environment.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/36)

### CODE REVIEW

**Comment by nkinkade** [comment]
Two small comments.

---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 35 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6VphGoW_b-Xtx8Jc3:-Ku6VphHPMku7LslYOpe:bmhdcfy) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L35)):*
> ```YAML
>     repo: m-lab/scraper-sync
>     all_branches: true
>     condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push
> ```

Unrelated to this PR, so perhaps out of place, and feel free to ignore if so. But instead of saying `all_branches: true` and then having to specify which branch in the condition, would it be more efficient and clean to just do:

```
on:
  repo: m-lab/scraper-sync
  branch: master
  condition: "$TRAVIS_EVENT_TYPE == push"
```

---

*[.travis.yml, line 43 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6WR0lBvlNoWZYTJqv:-Ku6WR0mVt_tL2Z7Jnqv:b5ixoa9) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L43)):*
> ```YAML
>   on:
>     repo: m-lab/scraper-sync
>     tags: true
> ```

Could you add a TODO [similar to the one that @stephen-soltesz has in the prometheus-support repo](https://github.com/m-lab/prometheus-support/blob/master/.travis.yml#L86)... to enforce some sort of format on the tag? We're not likely to go tagging things lightly, but does seem sort of risky to push to production on nothing more than some random tag being applied to some random commit of the repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-:-Ku6XjcBoGb9QNwBmVQB:b-z0tvc)*

**Comment by pboothe** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 35 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6VphGoW_b-Xtx8Jc3:-Ku6_6StqSYbqVjB_jqL:b-dk68uj) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L35)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Unrelated to this PR, so perhaps out of place, and feel free to ignore if so. But instead of saying `all_branches: true` and then having to specify which branch in the condition, would it be more efficient and clean to just do:

```
on:
  repo: m-lab/scraper-sync
  branch: master
  condition: "$TRAVIS_EVENT_TYPE == push"
```
</blockquote></details>

I was told by soltesz that this reasonable-seeming thing doesn't work. That is, `condition` apparently disables the `branch` check. He and I then agreed that is was dumb that Travis works this way. Now I can apparently also include you in that club of agreement. ;)

---

*[.travis.yml, line 43 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6WR0lBvlNoWZYTJqv:-KuKSXZpiKriBrIzuhIR:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L43)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Could you add a TODO [similar to the one that @stephen-soltesz has in the prometheus-support repo](https://github.com/m-lab/prometheus-support/blob/master/.travis.yml#L86)... to enforce some sort of format on the tag? We're not likely to go tagging things lightly, but does seem sort of risky to push to production on nothing more than some random tag being applied to some random commit of the repo.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/36)*

**Comment by pboothe** [comment]
PTAL

**Comment by nkinkade** [comment]
:lgtm: . I made one comment about the `all_braches: true` thing... your mileage may vary (for reasons I couldn't explain). 

For my own information, and not blocking this PR: your `apk` commands are installing more things than the old `apt-get` commands. Is this just because `apk` may not do dependency resolving like `apt-get`?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 35 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6VphGoW_b-Xtx8Jc3:-KuL8Xe6mT2yMQCbg3eP:buim4wc) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L35)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I was told by soltesz that this reasonable-seeming thing doesn't work. That is, `condition` apparently disables the `branch` check. He and I then agreed that is was dumb that Travis works this way. Now I can apparently also include you in that club of agreement. ;)
</blockquote></details>

It *seems* to have worked for me in the [.travis.yml file in the m-lab/prometheus-snmp-exporer repo](https://github.com/m-lab/prometheus-snmp-exporter/blob/master/.travis.yml#L30). I've have so far only tested it with a sandbox deployment.  Maybe check again? Or don't, and just leave it with what you have, since you know that works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-:-KuL9HeDuwsdyVtGaNbH:bvu7rdt)*

**Comment by pboothe** [comment]
*[.travis.yml, line 35 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-Ku6VphGoW_b-Xtx8Jc3:-KuLmkVcaeF2-U-DAIjk:b-h25svh) ([raw file](https://github.com/m-lab/scraper-sync/blob/2c120fa5fa430ede4a62819ffd2ff14b982f78ab/.travis.yml#L35)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It *seems* to have worked for me in the [.travis.yml file in the m-lab/prometheus-snmp-exporer repo](https://github.com/m-lab/prometheus-snmp-exporter/blob/master/.travis.yml#L30). I've have so far only tested it with a sandbox deployment.  Maybe check again? Or don't, and just leave it with what you have, since you know that works.
</blockquote></details>

I'd prefer to leave this one alone for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/36)*

**Comment by pboothe** [comment]
The base image of Alpine Linux has far fewer things pre-installed. It turns out that two of them (go-tools godep) are still overkill and can be removed, but for the rest, what you are seeing is the difference between the base image of Debian and the base image of Alpine Linux. On the positive side, the Docker image now is 100-200 MB instead of 700ish MB.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/36#-:-KuLRy_vUZk9_6TqdqYW:bn6mmm6)*

**Pull request merged**
