### PR TITLE
Only export current sites

### PR DESCRIPTION
**Pull request by pboothe**
Omit retired sites from the export to Prometheus

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/17)

### CODE REVIEW

**Comment by pboothe** [comment]
Tragically, due to the inclusion of the operator repo, test coverage is dropping from 100% down to the seventies.

**Comment by stephen-soltesz** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sync.py, line 401 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmKbaohR1xK7U9znVd:-KmmKbaohR1xK7U9znVe:b-59ot8k) ([raw file](https://github.com/m-lab/scraper-sync/blob/9ed7d1346330ac252770609763e973d6086877c3/sync.py#L401)):*
> ```Python
>             rsync_host = experiment.hostname(node)
>             for rsync_module in experiment['rsync_modules']:
>                 url = 'rsync://' + rsync_host + ':7999/' + rsync_module
> ```

Is there a way to generate this list from the same set of machines that match the scraper deploy.sh patterns? My hope is that we can have a 1:1 correspondence between scraper and scraper-sync. As written, if I understand correctly, this will include all current node experiments and rsync modules.

https://github.com/m-lab/scraper/blob/master/deploy.sh#L72

---

*[sync_test.py, line 360 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-Kmlz51PUJrSsCk-zA40:-Kmlz51QrghK2zrtLoQi:b-5mhoke) ([raw file](https://github.com/m-lab/scraper-sync/blob/9ed7d1346330ac252770609763e973d6086877c3/sync_test.py#L360)):*
> ```Python
> 
>     def test_get_currently_deployed_rsync_urls(self):
>         self.assertIn('rsync://utility.mlab.mlab4.nuq0t.measurement-lab.org'
> ```

nuq0t is or will be retired real soon now. The machines are shutdown. If the names are still there that may be a bug.

Is it intentional to use such a site?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/17)*

**Comment by pboothe** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sync_test.py, line 360 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-Kmlz51PUJrSsCk-zA40:-KmmOmnRGtjhYcfCWEPg:box1k5r) ([raw file](https://github.com/m-lab/scraper-sync/blob/9ed7d1346330ac252770609763e973d6086877c3/sync_test.py#L360)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nuq0t is or will be retired real soon now. The machines are shutdown. If the names are still there that may be a bug.

Is it intentional to use such a site?
</blockquote></details>

Nope. I just chose poorly. I'll choose the much-more-recent atl06 instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/17)*

**Comment by pboothe** [comment]
I have addressed your comments, and, in the process, this PR exploded. PTAL.

**Comment by stephen-soltesz** [comment]
:lgtm: I think this is all fine. Please add a few additional comments explaining the logic in the tests.

---

Reviewed 4 of 7 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[deploy.sh, line 65 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-Kmmfk6AmjlGzcK252qq:-Kmmfk6AmjlGzcK252qr:bc9ds7s) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/deploy.sh#L65)):*
> ```Shell
>   CLUSTER=scraper-cluster-${SANDBOXSUFFIX}
>   ZONE=us-central1-a
>   NODE_PATTERN_FILE=sandbox-nodes.txt
> ```

Why is this path different?

---

*[sync_test.py, line 297 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmkZPv80UbFwrMEtKa:-KmmkZPv80UbFwrMEtKb:b-uprns3) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L297)):*
> ```Python
>         mock_client.query().fetch.return_value = self.test_datastore_data
> 
>         rsync_urls_with_bad_value_added = set([
> ```

Please add comments describing this step and the one below.

---

*[sync_test.py, line 302 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmkbvgXM15uhpyA3m-:-KmmkbvgXM15uhpyA3m0:b-hqpe48) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L302)):*
> ```Python
>             'operator/plsync/staging_patterns.txt'))
> 
>         patcher = mock.patch('sync.get_currently_deployed_rsync_urls')
> ```

Please add a comment describing this.

---

*[sync_test.py, line 325 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmminFzO9lcedFLQwyL:-KmminFzO9lcedFLQwyM:bqt57sz) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L325)):*
> ```Python
>         mock_client = mock.Mock()
>         mock_datastore.Client.return_value = mock_client
>         self.test_datastore_data.append(
> ```

Please add a comment saying something like "Adding a datastore entry for a site that should no longer be published, to confirm that it is filtered from exported metrics."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-:-KmmknFgsyV94tHqsvcJ:b-5jmec3)*

**Comment by pboothe** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[deploy.sh, line 65 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-Kmmfk6AmjlGzcK252qq:-KmmmiF8MM-tL4HqsRiX:b-prj8u5) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/deploy.sh#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why is this path different?
</blockquote></details>

Because there is no standard subset of sandbox nodes, so the person who wants to do sandbox stuff needs to create it themselves.

---

*[sync.py, line 401 at r1](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmKbaohR1xK7U9znVd:-KmmmfhVifmGg2naGL7c:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/9ed7d1346330ac252770609763e973d6086877c3/sync.py#L401)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there a way to generate this list from the same set of machines that match the scraper deploy.sh patterns? My hope is that we can have a 1:1 correspondence between scraper and scraper-sync. As written, if I understand correctly, this will include all current node experiments and rsync modules.

https://github.com/m-lab/scraper/blob/master/deploy.sh#L72
</blockquote></details>

Done.

---

*[sync_test.py, line 297 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmkZPv80UbFwrMEtKa:-KmmmcaCFaxSfUcEr5qz:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L297)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add comments describing this step and the one below.
</blockquote></details>

Done.

---

*[sync_test.py, line 302 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmmkbvgXM15uhpyA3m-:-KmmmdpiMTNnTapLCVgp:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L302)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment describing this.
</blockquote></details>

Done.

---

*[sync_test.py, line 325 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/17#-KmminFzO9lcedFLQwyL:-KmmmeEVSTJfVicY8xkT:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/52c9c6f5012b29e373eff1652390117c10def083/sync_test.py#L325)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment saying something like "Adding a datastore entry for a site that should no longer be published, to confirm that it is filtered from exported metrics."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/17)*

**Pull request merged**
