### PR TITLE
sync_test now works with the latest testfixtures

### PR DESCRIPTION
**Pull request by pboothe**
Updated the submodules, just to keep things current.
Fixed a new linter error involving the import order.

This also fixes the build breakage that was causing Travis to email me that the build was broken.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/53)

### CODE REVIEW

**Comment by pboothe** [comment]
Fixes #52

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[sync_test.py, line 269 at r1](https://reviewable.io/reviews/m-lab/scraper-sync/53#-LAsvBcfBspqIjrVVeu_:-LAsvBcfBspqIjrVVeua:bcc75y8) ([raw file](https://github.com/m-lab/scraper-sync/blob/542b79e81aed901c18dd3c9c833187464ce35334/sync_test.py#L269)):*
> ```Python
>     @mock.patch.object(sync, 'datastore')
>     def test_prometheus_forwarding_and_retired_sites(self, mock_datastore,
>                                                      _log):
> ```

Was it your intention to prepend an underscore to the `log` parameter? Not a big deal, but `log` doesn't have an underscore in `test_prometheus_forwarding_with_bad_data`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/53#-:-LAsvWfjCqY4zmpsGUFt:bnfp4nl)*

**Review by nkinkade — APPROVED** [review]
LGTM

**Comment by pboothe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sync_test.py, line 269 at r1](https://reviewable.io/reviews/m-lab/scraper-sync/53#-LAsvBcfBspqIjrVVeu_:-LAsviXl8kXyPZ22Wdz-:b96cpwb) ([raw file](https://github.com/m-lab/scraper-sync/blob/542b79e81aed901c18dd3c9c833187464ce35334/sync_test.py#L269)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Was it your intention to prepend an underscore to the `log` parameter? Not a big deal, but `log` doesn't have an underscore in `test_prometheus_forwarding_with_bad_data`.
</blockquote></details>

Yes! The underscore is an indication to the linter that the name will never be used in the function body, and that this is on purpose. Without the underscore, I would get a linter warning that I had declared the variable `log` but never used it. A handy trick!

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/53)*

**Pull request merged**
