### PR TITLE
Add status url to the Scraper-Sync service

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/scraper-sync/38)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 5 of 9 files at r2.
Review status: 5 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJyB9QcZxawRxC-W6:-KuVJyB9QcZxawRxC-W7:b-p5k63o) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/.travis.yml#L1)):*
> ```YAML
> language: python
> ```

Please add brief header describing the docker aspects of this, or perhaps

---

*[.travis.yml, line 13 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKL34qZDDECDXdgL1:-KuVKL34qZDDECDXdgL2:b-dbi9dv) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/.travis.yml#L13)):*
> ```YAML
> install:
> - pip install coveralls
> - $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl
> ```

Is this gcloud line still required?

---

*[pre-commit.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVLTQASkw5o3QHaZ0M:-KuVLTQASkw5o3QHaZ0N:bigzmxf) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/pre-commit.sh#L11)):*
> ```Shell
> 
> docker build . -f Dockerfile -t sync
> docker build . -f TestDockerfile -t synctest
> ```

Could you structure this so that TestDockerfile builds on top of the Dockerfile container?  Otherwise there is risk of these getting out of sync, and not catching a bug introduced in Dockerfile.

---

*[README.md, line 4 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKrR4NVf63DwtQUo8:-KuVKrR4NVf63DwtQUo9:bypnpme) ([raw file](https://github.com/m-lab/scraper-sync/blob/847cdf8fa9551fb45a69f79c98dc3e5f30a8db8c/README.md#L4)):*
> ```Markdown
> |:------:|:------------:|:--------:|
> | Master | [Build Status](https://travis-ci.org/m-lab/scraper-sync) | [Coverage Status](https://coveralls.io/github/m-lab/scraper-sync?branch=master) |
> | Staging | [Build Status](https://travis-ci.org/m-lab/scraper-sync) | [Coverage Status](https://coveralls.io/github/m-lab/scraper-sync?branch=staging) |
> ```

Does staging status no longer work?  Or is it no longer needed because of deploy on tag?

---

*[README.md, line 20 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKaAPpemd0p2AGATG:-KuVKaAPpemd0p2AGATH:b-ta5lwc) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/README.md#L20)):*
> ```Markdown
> URL `/json_status?rsync_url=mlab1`
> 
> The `rsync_url` argument is compared the URL of every rsync endpoint using
> ```

Is it too late to change rsync_url to rsync_filter or host_filter?

---

*[test_for_inside_container.sh, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJCw4gOoW6Ka77gjA:-KuVJCw4gOoW6Ka77gjB:b-zcdokf) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/test_for_inside_container.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Cool.

Please rename start_datastore_emulator_for_test.sh
(or something similar)

---

*[TestDockerfile, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJTPhKpadtE3Y5yDD:-KuVJTPiF-31QuZV6qRe:bdpzql0) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/TestDockerfile#L1)):*
> ```
> FROM sync
> ```

Please add some header comments describing purpose, and summarizing what it is *installing"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38)*

**Comment by gfr10598** [comment]
Reviewed 1 of 4 files at r1, 4 of 9 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[sync_test.py, line 47 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVM3XPajffxK1ljIha:-KuVM3XPajffxK1ljIhb:bkdg3kd) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L47)):*
> ```Python
> 
>     Used to avoid the need for auth entirely when using local versions of cloud
>     services.
> ```

Add a link to the GCServices tests that do this, for reference?

---

*[sync_test.py, line 62 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVMuMDvm_ReUZJPOOh:-KuVMuMDvm_ReUZJPOOi:b6pckdc) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L62)):*
> ```Python
> 
> 
> DATASTORE_DATA = [
> ```

BTW, good restructuring.

---

*[sync_test.py, line 174 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVNTAjKymNCNppQhJ0:-KuVNTAjKymNCNppQhJ1:b7gwmy3) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L174)):*
> ```Python
>     def test_get_fleet_data_subsets(self):
>         prg01_switch = {
>             'dropboxrsyncaddress': 'rsync://utility.mlab.mlab4.prg01.'
> ```

Is it time to drop the "dropbox" prefix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38)*

**Comment by pboothe** [comment]
Associated with https://github.com/m-lab/ops-tracker/issues/129 and https://github.com/m-lab/ops-tracker/issues/208

**Comment by pboothe** [comment]
PTAL

---

Review status: 4 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[.travis.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJyB9QcZxawRxC-W6:-KuW4ghjDe0c2Y5UgZo0:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/.travis.yml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add brief header describing the docker aspects of this, or perhaps
</blockquote></details>

Done.

---

*[.travis.yml, line 13 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKL34qZDDECDXdgL1:-KuW4hGQpg1gBEZYkbOv:b6jay4k) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/.travis.yml#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this gcloud line still required?
</blockquote></details>

Yes, added a comment.

---

*[pre-commit.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVLTQASkw5o3QHaZ0M:-KuW4msBNFmEt0fg871T:b-dxralp) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/pre-commit.sh#L11)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you structure this so that TestDockerfile builds on top of the Dockerfile container?  Otherwise there is risk of these getting out of sync, and not catching a bug introduced in Dockerfile.
</blockquote></details>

That is how things are already structured. `TestDockerfile` is based on the `sync` image.

---

*[README.md, line 4 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKrR4NVf63DwtQUo8:-KuW4x80qKOyJuHXOrkR:b-rs1a9m) ([raw file](https://github.com/m-lab/scraper-sync/blob/847cdf8fa9551fb45a69f79c98dc3e5f30a8db8c/README.md#L4)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Does staging status no longer work?  Or is it no longer needed because of deploy on tag?
</blockquote></details>

The staging branch is deprecated thanks to deploy-on-tag.

---

*[README.md, line 20 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVKaAPpemd0p2AGATG:-KuW51pYDAHMSZnVDTx-:b-2zj04) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/README.md#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is it too late to change rsync_url to rsync_filter or host_filter?
</blockquote></details>

Not at all. It's actually an `rsync_filter`, because it filters based on the complete rsync url, which includes a path, so that's the name I switched it to.

---

*[sync_test.py, line 47 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVM3XPajffxK1ljIha:-KuW8jIlILkBfiEuxy7j:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L47)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a link to the GCServices tests that do this, for reference?
</blockquote></details>

Done.

---

*[sync_test.py, line 62 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVMuMDvm_ReUZJPOOh:-KuW6sdkRRVWMnW0BK-J:b-ucfknh) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, good restructuring.
</blockquote></details>

Thanks!

---

*[sync_test.py, line 174 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVNTAjKymNCNppQhJ0:-KuW6zaJ3hTKxy-VjOdN:b-ur56ru) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/sync_test.py#L174)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is it time to drop the "dropbox" prefix?
</blockquote></details>

No. Such a renaming is a secretly-large task as it requires deploying a new scraper as well, and it shouldn't even be attempted until we remove the spreadsheet code entirely, instead of just adding this new method of getting at the data.

---

*[TestDockerfile, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJTPhKpadtE3Y5yDD:-KuW8G65n4dDezqoRGTU:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/TestDockerfile#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add some header comments describing purpose, and summarizing what it is *installing"
</blockquote></details>

Done.

---

*[test_for_inside_container.sh, line 1 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVJCw4gOoW6Ka77gjA:-KuW8fDWAAjcHZWzOjpm:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/test_for_inside_container.sh#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Cool.

Please rename start_datastore_emulator_for_test.sh
(or something similar)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-:-KuWBibYkRpTw3bxNHep:bb71pro)*

**Comment by gfr10598** [comment]
:lgtm:  ... after one minor README update.

---

Reviewed 1 of 7 files at r3.
Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pre-commit.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVLTQASkw5o3QHaZ0M:-KuWEsdWyeiSnmfwahkc:bb6t5oh) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/pre-commit.sh#L11)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

That is how things are already structured. `TestDockerfile` is based on the `sync` image.
</blockquote></details>

D'oh

---

*[README.md, line 20 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuWF9RoNu3YmLIubr9L:-KuWF9RoNu3YmLIubr9M:bhmwc59) ([raw file](https://github.com/m-lab/scraper-sync/blob/98e662ede6cbc239effcf9d1fb8adba50826d89d/README.md#L20)):*
> ```Markdown
> URL `/json_status?rsync_url=mlab1`
> 
> The `rsync_url` argument is compared the URL of every rsync endpoint using
> ```

Please update the README reference too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-:-KuWFY3wpeU0srdW3uS_:b9o4mzj)*

**Comment by gfr10598** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38)*

**Comment by pboothe** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pre-commit.sh, line 11 at r2](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuVLTQASkw5o3QHaZ0M:-KuWG2GLSgJKGSqarJbb:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/f95cc1e0f488628990c6fa5e8304bae0d11f372d/pre-commit.sh#L11)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

D'oh
</blockquote></details>

Done.

---

*[README.md, line 20 at r3](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-KuWF9RoNu3YmLIubr9L:-KuWG3DwzI2pL0KwRxrT:b-896fix) ([raw file](https://github.com/m-lab/scraper-sync/blob/98e662ede6cbc239effcf9d1fb8adba50826d89d/README.md#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please update the README reference too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38)*

**Comment by pboothe** [comment]
Thanks!

---

Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38#-:-KuWG7TEUEc5QLTcnLyl:b-ucfknh)*

**Comment by gfr10598** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/scraper-sync/38)*

**Review by gfr10598 — APPROVED** [review]

**Pull request merged**
